version: "3"

services:
  web:
    image: web
    build: .
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    command: bash -c "tail -f /dev/null"
    ports:
      - "5000:5000"
    # provide environment variables from .env file
    env_file:
      - .env
    networks:
      - heron-net
    volumes:
      - ./src:/server/src

networks:
  heron-net:
